---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  namespace: random-rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: rabbit
    port: 5672
    targetPort: 5672
  - name: rabbit-ui
    port: 80
    targetPort: 15672
  selector:
    app: random-rabbitmq
    component: rabbitmq

